### ISSUE TITLE
Searching breweries by latitude-longitude

### ISSUE THREAD

**Issue by subinkrishna** [chrisjm/openbrewerydb-gatsby#19]
# Feature request

## Overview

Add support for searching breweries by latitude & longitude. This is useful when we need to find the breweries closer to the current location of a user, especially in a mobile application. 

The API can look like `https://api.openbrewerydb.org/breweries?by_location=<latitude>,<longitude>` and output can be sorted by the distance.

(Not sure if this is the right place for API feature requests)

**Comment by chrisjm** [comment]
Hi, @subinkrishna ! Thanks for submitting this feature request!

This issue is covered by the following issue on the API repo: https://github.com/chrisjm/openbrewerydb-rails-api/issues/15

I'm going to close as a duplicate, but let me know if you have any questions or would like to contribute. Thanks!
